// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.profileCreationThreshold", "1896163212345");
user_pref("app.normandy.user_id", "749e46c6-f932-a143-b972-12911b656775");
user_pref("app.update.download.attempts", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1599199212);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1599199572);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1599199452);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1599199332);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1599199242);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1599199181);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.discoverystream.personalization.overrideVersion", 1);
user_pref("browser.newtabpage.activity-stream.impressionId", "{db0b38f7-291f-0b4b-a877-02f3455df917}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1599199243330");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1599201045330");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1599199183952");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1599202783952");
user_pref("browser.search.region", "US");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 1048);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200818235255");
user_pref("browser.startup.homepage_override.mstone", "80.0");
user_pref("browser.startup.lastColdStartupCheck", 1599199183);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1599199183209");
user_pref("distribution.iniFile.exists.appversion", "80.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.mode", 2);
user_pref("doh-rollout.self-enabled", true);
user_pref("dom.push.userAgentID", "c8b893f209ba4d25ac3c4cafee4d7e97");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "80.0");
user_pref("extensions.lastPlatformVersion", "80.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"d2f03c9a-64de-bc40-b05b-c4de9f474b15\",\"formautofill@mozilla.org\":\"181f9a77-7d50-f54a-aab6-3a2d6c6d0ee0\",\"screenshots@mozilla.org\":\"a0054459-64f1-7b48-94c8-809bac39fc64\",\"webcompat-reporter@mozilla.org\":\"786592c8-021d-8f49-a587-3d08840705fd\",\"webcompat@mozilla.org\":\"b55ef1cd-88d0-2740-8cac-727ffacf756d\",\"default-theme@mozilla.org\":\"d857679f-9070-984d-b36a-d20db35475c6\",\"google@search.mozilla.org\":\"5145f519-e693-4c4b-86b6-e22a4517a00b\",\"amazondotcom@search.mozilla.org\":\"c6eb55fd-2b6d-5446-a103-b937944aef8e\",\"wikipedia@search.mozilla.org\":\"9c1c0481-592f-6948-b2a5-c7475898b9a4\",\"bing@search.mozilla.org\":\"af603a22-2855-d14f-a1a1-2ca2e987d840\",\"ddg@search.mozilla.org\":\"e393690e-e8d1-2e4c-8447-fa6e7a7c267b\",\"ebay@search.mozilla.org\":\"bf29be80-1ed8-6a48-8541-3c79ecd9a2f2\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.disable_button.openCertManager", false);
user_pref("security.sandbox.content.tempDirSuffix", "fe1fa499-4f0d-464e-9238-b71270e6a024");
user_pref("security.sandbox.plugin.tempDirSuffix", "6e4fa8be-bed0-a148-ac58-a36071f35355");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1599199181);
user_pref("toolkit.telemetry.cachedClientID", "ed55c099-d6f3-4e43-bc5c-c7cd7650dfb4");
user_pref("toolkit.telemetry.previousBuildID", "20200818235255");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
