stages:
  - production

deploy_production:
  stage: production
  variables:
    ID_RSA_NAME: $CI_PROJECT_PATH_SLUG"_prod"
  environment:
    name: production
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$PROD_SSH_KEY" > ~/.ssh/$ID_RSA_NAME
    - chmod 600 ~/.ssh/$ID_RSA_NAME
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - >
    - ssh -i "~/.ssh/$ID_RSA_NAME" "root"@"$PROD_SERVER_HOST" "cd $PROD_PATH
      && docker exec scraping-env_scrapyd_1 bash -c 'cd /opt/forumparser; git pull;'
      && exit"
  only:
    - master


