before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -t rsa ${HOST} >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

deploy_production:
  type: deploy
  environment:
    name: production
  script:
    - ssh -tt root@${HOST} "docker exec -it scraping-env_scrapyd_1 bash -c 'cd /opt/forumparser; git pull;'"
  only:
    - master