deploy_production:
    stage: production
    variables:
        ID_RSA_NAME: "gitcicdkey"
    environment:
        name: production
        url: project_url
    before_script:
        - mkdir -p ~/.ssh
        - echo -e "$PROD_SSH_KEY" > ~/.ssh/$ID_RSA_NAME
        - chmod 600 ~/.ssh/$ID_RSA_NAME
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    script:
        - ssh -i "~/.ssh/$ID_RSA_NAME" "$PROD_USER_NAME"@"$PROD_SERVER_HOST" "cd $PROD_PATH && git checkout master && git pull origin master && exit"
    only:
        - master
